# Generated by Django 5.0.6 on 2024-06-22 13:51

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Table',
            fields=[
                ('project_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=700)),
                ('budget', models.IntegerField()),
                ('isApproved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('delivery_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('attachments', models.FileField(null=True, upload_to='')),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rasied_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=700)),
                ('escalation_level', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('solved_time', models.DateTimeField(null=True)),
                ('deadline_time', models.DateTimeField(default=app.models.default_deadline)),
            ],
        ),
        migrations.CreateModel(
            name='User_Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('level', models.CharField(default='Admin', editable=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User_Higher',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('level', models.CharField(default='Higher', editable=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User_Ngo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('level', models.CharField(default='Ngo', editable=False, max_length=5)),
            ],
        ),
    ]
