# Generated by Django 5.0.6 on 2024-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_higher',
            name='level',
            field=models.CharField(default='Higher', editable=False, max_length=50),
        ),
    ]
