# Generated by Django 5.0.6 on 2024-06-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_higher_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='rasied_by',
            new_name='raised_by',
        ),
    ]
